{"uuid": "11ef0c8b-b5b2-4418-8068-cb2d42393391", "children": ["8edff788-0d7f-430f-a7ab-3b51a7ea88a2"], "befores": [{"name": "_xunit_setup_method_fixture_TestActionChains", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"F:\\Python36\\python_env\\yyl\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"F:\\Python36\\python_env\\yyl\\lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"F:\\Python36\\python_env\\yyl\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"F:\\Python36\\python_env\\yyl\\lib\\site-packages\\_pytest\\python.py\", line 884, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"F:\\Python36\\python_env\\yyl\\lib\\site-packages\\_pytest\\python.py\", line 769, in _call_with_optional_argument\n    func()\n  File \"H:\\PycharmProject\\test_pytest\\test_ActionChains.py\", line 11, in setup\n    self.driver = webdriver.Chrome()\n  File \"F:\\Python36\\python_env\\yyl\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"F:\\Python36\\python_env\\yyl\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 83, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1649064158882, "stop": 1649064158882}], "start": 1649064158882, "stop": 1649064158992}