{"uuid": "51af7a9e-68bc-4b88-a396-01ff0832e4b9", "children": ["5dce09cc-f9e9-4135-9530-d6fa5a19f45c"], "befores": [{"name": "_xunit_setup_method_fixture_TestActionChains", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"F:\\Python36\\python_env\\yyl\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"F:\\Python36\\python_env\\yyl\\lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"F:\\Python36\\python_env\\yyl\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"F:\\Python36\\python_env\\yyl\\lib\\site-packages\\_pytest\\python.py\", line 884, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"F:\\Python36\\python_env\\yyl\\lib\\site-packages\\_pytest\\python.py\", line 769, in _call_with_optional_argument\n    func()\n  File \"H:\\PycharmProject\\test_pytest\\test_ActionChains.py\", line 11, in setup\n    self.driver = webdriver.Chrome()\n  File \"F:\\Python36\\python_env\\yyl\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"F:\\Python36\\python_env\\yyl\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 83, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1649063921395, "stop": 1649063921395}], "start": 1649063921395, "stop": 1649063921505}