{"name": "test_add_error[Ca_add_012]", "status": "broken", "statusDetails": {"message": "NameError: name 'ERROR' is not defined", "trace": "self = <test_cal.TestCal object at 0x0000015B89CEEB30>, a = '文', b = 9.3\nexpect = 'ERROR'\n\n    @pytest.mark.parametrize(\"a,b,expect\", get_errvalue(), ids=get_ekeys())\n    def test_add_error(self, a, b, expect):\n        # 定义一个对象calc\n        calc = Calculator()\n        # result 为实际结果\n>       with pytest.raises(eval(expect)) as e:\n\ntest_cal.py:40: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n>   ???\nE   NameError: name 'ERROR' is not defined\n\n<string>:1: NameError"}, "parameters": [{"name": "a", "value": "'文'"}, {"name": "b", "value": "9.3"}, {"name": "expect", "value": "'ERROR'"}], "start": 1648450767242, "stop": 1648450767242, "uuid": "543ae047-9e43-4ab7-91b8-a3361eca2c53", "historyId": "43ec30340d6cf91fb6059eb332dcac96", "testCaseId": "a3bfe621045782c9ea9a5de99829cd04", "fullName": "test_pytest.test_cal.TestCal#test_add_error", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('def_fixture')"}, {"name": "parentSuite", "value": "test_pytest"}, {"name": "suite", "value": "test_cal"}, {"name": "subSuite", "value": "TestCal"}, {"name": "host", "value": "IT-L-YANGYL"}, {"name": "thread", "value": "18820-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest.test_cal"}]}