{"name": "test_add_error[Ca_add_012]", "status": "broken", "statusDetails": {"message": "UnboundLocalError: local variable 'resulted' referenced before assignment", "trace": "self = <test_cal.TestCal object at 0x0000018D17B0B9A0>, numa = '文', numb = 9.3\nconclusion = 'TypeError'\n\n    @pytest.mark.parametrize(\"numa,numb,conclusion\", get_errvalue(), ids=get_ekeys())\n    def test_add_error(self, numa, numb, conclusion):\n        # 定义一个对象calc\n        calc = Calculator()\n        # result 为实际结果\n        with pytest.raises(eval(conclusion)) as e:\n            resulted = calc.add(numa, numb)\n>       print(resulted)\nE       UnboundLocalError: local variable 'resulted' referenced before assignment\n\ntest_cal.py:41: UnboundLocalError"}, "parameters": [{"name": "numa", "value": "'文'"}, {"name": "numb", "value": "9.3"}, {"name": "conclusion", "value": "'TypeError'"}], "start": 1648452412744, "stop": 1648452412744, "uuid": "7a6b33ae-276e-449a-a18e-b9e27d32dc2a", "historyId": "43ec30340d6cf91fb6059eb332dcac96", "testCaseId": "a3bfe621045782c9ea9a5de99829cd04", "fullName": "test_pytest.test_cal.TestCal#test_add_error", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('def_fixture')"}, {"name": "parentSuite", "value": "test_pytest"}, {"name": "suite", "value": "test_cal"}, {"name": "subSuite", "value": "TestCal"}, {"name": "host", "value": "IT-L-YANGYL"}, {"name": "thread", "value": "12588-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest.test_cal"}]}