{"name": "test_add[2-3-4]", "status": "failed", "statusDetails": {"message": "AssertionError: assert (2 + 3) == 4", "trace": "self = <test_cal.TestCal object at 0x000001FE2E878D90>, num1 = 2, num2 = 3\nexpected = 4\n\n    @pytest.mark.parametrize(\"num1,num2,expected\", [[1, 1, 2], [2, 3, 4]])\n    def test_add(self, num1, num2, expected):\n>       assert num1 + num2 == expected\nE       assert (2 + 3) == 4\n\ntest_cal.py:25: AssertionError"}, "parameters": [{"name": "num1", "value": "2"}, {"name": "num2", "value": "3"}, {"name": "expected", "value": "4"}], "start": 1648202717276, "stop": 1648202717276, "uuid": "3924d7ea-c4c2-4fc9-bb2e-9fb7e273945b", "historyId": "4c4fda3027a7778ce19531b161c665d8", "testCaseId": "a6e0767392ecb02e01928ce756d83f54", "fullName": "test_pytest.test_cal.TestCal#test_add", "labels": [{"name": "parentSuite", "value": "test_pytest"}, {"name": "suite", "value": "test_cal"}, {"name": "subSuite", "value": "TestCal"}, {"name": "host", "value": "IT-L-YANGYL"}, {"name": "thread", "value": "5248-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest.test_cal"}]}