{"name": "test_eval[2]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 in [3, 4, 5, 7, 8]", "trace": "yy = 2\n\n    @pytest.mark.parametrize(\"yy\", [3, 4, 5, 2])\n    def test_eval(yy):\n>       assert yy in search_list\nE       assert 2 in [3, 4, 5, 7, 8]\n\ntest_expectation.py:13: AssertionError"}, "parameters": [{"name": "yy", "value": "2"}], "start": 1647926627611, "stop": 1647926627611, "uuid": "abce7890-3e78-4043-bd56-02b0c819eb2c", "historyId": "ecb873f0253aa2452269ad03e0319dfe", "testCaseId": "ff6166714df71c7f259a948c6e62680c", "fullName": "test_pytest.test_expectation#test_eval", "labels": [{"name": "parentSuite", "value": "test_pytest"}, {"name": "suite", "value": "test_expectation"}, {"name": "host", "value": "IT-L-YANGYL"}, {"name": "thread", "value": "9900-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest.test_expectation"}]}