{"name": "test_add_error[Ca_add_012]", "status": "broken", "statusDetails": {"message": "UnboundLocalError: local variable 'result' referenced before assignment", "trace": "self = <test_cal.TestCal object at 0x00000143B78AEB00>, a = '文', b = 9.3\nexpect = 'TypeError'\n\n    @pytest.mark.parametrize(\"a,b,expect\", get_errvalue(), ids=get_ekeys())\n    def test_add_error(self, a, b, expect):\n        # 定义一个对象calc\n        calc = Calculator()\n        # result 为实际结果\n        with pytest.raises(eval(expect)) as e:\n            result = calc.add(a, b)\n        # assert e.typename == expect\n>       assert result == 'TypeError'\nE       UnboundLocalError: local variable 'result' referenced before assignment\n\ntest_cal.py:42: UnboundLocalError"}, "parameters": [{"name": "a", "value": "'文'"}, {"name": "b", "value": "9.3"}, {"name": "expect", "value": "'TypeError'"}], "start": 1648451115735, "stop": 1648451115749, "uuid": "69520f9a-9433-4663-982b-6a68336db92f", "historyId": "43ec30340d6cf91fb6059eb332dcac96", "testCaseId": "a3bfe621045782c9ea9a5de99829cd04", "fullName": "test_pytest.test_cal.TestCal#test_add_error", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('def_fixture')"}, {"name": "parentSuite", "value": "test_pytest"}, {"name": "suite", "value": "test_cal"}, {"name": "subSuite", "value": "TestCal"}, {"name": "host", "value": "IT-L-YANGYL"}, {"name": "thread", "value": "21408-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest.test_cal"}]}