{"uuid": "fcc96ff1-9ef9-4ae0-b5f5-5a9660df475b", "children": ["6bec5b21-6a3a-4309-bf6d-15e86cc73d76"], "befores": [{"name": "_xunit_setup_method_fixture_TestWait", "status": "broken", "statusDetails": {"message": "TypeError: 'module' object is not callable\n", "trace": "  File \"C:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\yilin.yang\\AppData\\Roaming\\Python\\Python310\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\yilin.yang\\AppData\\Roaming\\Python\\Python310\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\yilin.yang\\AppData\\Roaming\\Python\\Python310\\site-packages\\_pytest\\python.py\", line 893, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"C:\\Users\\yilin.yang\\AppData\\Roaming\\Python\\Python310\\site-packages\\_pytest\\python.py\", line 778, in _call_with_optional_argument\n    func()\n  File \"E:\\PycharmProject\\test_pytest\\test_wait.py\", line 9, in setup\n    self.driver = webdriver.chrome()\n"}, "start": 1648632244282, "stop": 1648632244282}], "start": 1648632244282, "stop": 1648632244340}